language: php
php: 
- 5.3
- 5.4
matrix: 
  include: 
    - env: DB=mysql TYPO3=master INTEGRATION=master-placements COVERAGE=1
      php: 5.5
services: 
- memcached
env: 
  global: 
    secure: S8QheEMVpSRsPPIhYQZ4tUCTbxpM7csZ0GydJaPY8p/FAEnZLiH6xcsiTGKOljva5HDelCdBvunaWtUO/+CdKIgsdbQGbqc1aWmG6gr+ShQk4X3KzeAA91AFmkJOR6Jv69lUTm6Uo9AKs1JtuVZsOa1aoOmfApohqFuXsRBNXlg=
  matrix: 
  - DB=mysql TYPO3=master INTEGRATION=master-placements COVERAGE=0
script: 
- >
  if [[ "$COVERAGE" == "0" ]]; then 
    ./bin/phpunit --colors -c typo3conf/ext/placements/Tests/Build/UnitTests.xml
  fi
#- phpCodeSniff
#- if [[ "$COVERAGE" == "1" ]]; then php $PWD/typo3conf/ext/phpunit/Composer/vendor/bin/phpunit --process-isolation  --bootstrap typo3/sysext/core/Build/FunctionalTestsBootstrap.php typo3conf/ext/placements/Tests/Functional/; fi
- >
  if [[ "$COVERAGE" == "1" ]]; then
    echo;
    echo "Running unit tests";
    ./bin/phpunit --coverage-clover=build/artifacts/coverage/clover.xml -c typo3conf/ext/placements/Tests/Build/UnitTests.xml
  fi
before_script: 
- cd ..
- mkdir -p build/artifacts/coverage
- mkdir build/artifacts/logs
- git clone --single-branch --branch $INTEGRATION --depth 1 git://github.com/dwenzel/TYPO3-Travis-Integration.git build-environment
- git clone --single-branch --branch $TYPO3 --depth 1 https://github.com/TYPO3/TYPO3.CMS.git core
- mv core/* .
- composer self-update
- composer install
- mkdir -p uploads typo3temp typo3conf/ext
- mv placements ./typo3conf/ext
- source build-environment/install-helper.sh
#- if [[ "$TRAVIS_PHP_VERSION" != "5.5" ]]; then installPhpModule igbinary; fi
#- installPhpModule -y memcache
#- if [[ "$TRAVIS_PHP_VERSION" == "5.3" ]]; then installPhpModule -y apc; fi
#- if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS typo3_test;" -uroot; fi
#- if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS typo3_test;" -uroot; fi
#- if [[ "$DB" == "mysql" ]]; then mysql -uroot typo3_test < build-environment/Introduction/typo3conf/ext/introduction/Resources/Private/Subpackages/Introduction/Database/introduction.sql; fi
#- if [[ "$DB" == "mysql" && -f build-environment/dbimport/cache_tables.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/cache_tables.sql; fi
#- if [[ "$DB" == "mysql" && -f  build-environment/dbimport/cli_users.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/cli_users.sql; fi
#- if [[ "$DB" == "mysql" && -f  build-environment/dbimport/placements.sql ]]; then mysql -uroot typo3_test < build-environment/dbimport/placements.sql; fi
after_script:
- >
  if [[ "$COVERAGE" == "1" ]]; then
    rm composer.json;
    mv build-environment/composer.json ./;
    export COVERALLS_SERVICE_NAME=travis-ci;
    cp -R typo3conf/ext/placements/.git .;
    cp typo3conf/ext/placements/.coveralls.yml ./;
    wget http://getcomposer.org/composer.phar;
    php composer.phar update satooshi/php-coveralls --dev;
    echo;
    echo "Running coveralls";
    php vendor/bin/coveralls -v;
  fi
#- source build-environment/update-gh-pages.sh
