<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "placements"
 *
 * Auto generated by Extension Builder 2013-11-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Placement Service',
	'description' => 'Manage job offers and applications.',
	'category' => 'plugin',
	'author' => 'Dirk Wenzel, Michael Kasten',
	'author_email' => 'wenzel@webfox01.de, kasten@webfox01.de',
	'author_company' => 'AgenturWebfox GmbH, AgenturWebfox GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.6.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>
